# Generated by Django 4.0.5 on 2023-03-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='contactus',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
