# Generated by Django 4.0.5 on 2023-03-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_contactus_fname_contactus_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
