# Generated by Django 4.0.5 on 2023-03-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='lname',
        ),
    ]
