# Generated by Django 4.0.5 on 2023-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_contactus_fname_remove_contactus_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contactus',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
